"""Changed DB structure (Added Grade entity + seeded new data)

Revision ID: 76ad2ef61881
Revises: cb5fde5c4d5e
Create Date: 2026-06-06 02:20:09.984852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76ad2ef61881'
down_revision: Union[str, Sequence[str], None] = 'cb5fde5c4d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_m2m_course', 'score')
    op.drop_column('student_m2m_course', 'created')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_m2m_course', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('student_m2m_course', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
